language: node_js
node_js:
  - '0.10'
before_script:
  - npm install --quiet -g grunt-cli karma codeclimate-test-reporter
  - npm install
script: grunt build
after_success:
    - codeclimate-test-reporter < ./gen/coverage/report/lcov.info
    - ./publish.sh
env:
  global:
    - GH_REF: github.com/zeusjs/utils.git
    - secure: xoxG8T/iW/g3bzng43XPEfrMGbM3meHhmQrre0emt32ZF4O0MHA9P877s6rRNcwoAflBmCcgtbqYWoP+sfLwiBMQ4Dh6fxjKq1aGspBxYqakMnMXzdHedeWzcu1NlNsj8Doqvr1JhqjhwxQVgMSpTtYwan8MAeIF/XDjsXeAW/w=
    - secure: adXTQtY8Jru+zgcjaPDsNXhhZ9GxHP4B51mLHPbQtAH+riE5HLfwjOYGLaR3q+8GdVsrrfw22F7x2WVUWqEBQ3dlr9+UrSiOb7sxM7HMnlu4Zb1igptMkFh/R815CmTSwMwNd/Y1MxoJR+Z9+G378oJH+zUQzSLXM4KN0cUmJYg=
